/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_user (void)
{
  GtkWidget *ajout_user;
  GtkWidget *fixed1;
  GtkWidget *entryNom_user;
  GtkWidget *entryPrenom_user;
  GtkObject *spinbuttonJour_user_adj;
  GtkWidget *spinbuttonJour_user;
  GtkObject *spinbuttonMois_user_adj;
  GtkWidget *spinbuttonMois_user;
  GtkObject *spinbuttonAnnee_user_adj;
  GtkWidget *spinbuttonAnnee_user;
  GtkWidget *entryCin_user;
  GtkObject *spinbuttonNumBV_user_adj;
  GtkWidget *spinbuttonNumBV_user;
  GtkObject *spinbuttonVote_user_adj;
  GtkWidget *spinbuttonVote_user;
  GtkWidget *buttonValide_user;
  GtkWidget *checkbuttonEtr_obs;
  GtkWidget *checkbuttonTun_obs;
  GtkWidget *radiobuttonFemme_user;
  GSList *radiobuttonFemme_user_group = NULL;
  GtkWidget *radiobuttonHomme_user;
  GtkWidget *comboboxprof_user;
  GtkWidget *comboboxApp_obs;
  GtkWidget *comboboxRole_user;
  GtkWidget *buttonAfficher_user;

  ajout_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_user), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_user), fixed1);

  entryNom_user = gtk_entry_new ();
  gtk_widget_show (entryNom_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom_user, 216, 48);
  gtk_widget_set_size_request (entryNom_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom_user), 8226);

  entryPrenom_user = gtk_entry_new ();
  gtk_widget_show (entryPrenom_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPrenom_user, 216, 112);
  gtk_widget_set_size_request (entryPrenom_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom_user), 8226);

  spinbuttonJour_user_adj = gtk_adjustment_new (1, 1, 31, 0.5, 10, 10);
  spinbuttonJour_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJour_user_adj), 0, 0);
  gtk_widget_show (spinbuttonJour_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonJour_user, 304, 160);
  gtk_widget_set_size_request (spinbuttonJour_user, 60, 27);

  spinbuttonMois_user_adj = gtk_adjustment_new (1, 1, 12, 0.5, 10, 10);
  spinbuttonMois_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_user_adj), 0, 0);
  gtk_widget_show (spinbuttonMois_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonMois_user, 392, 160);
  gtk_widget_set_size_request (spinbuttonMois_user, 60, 27);

  spinbuttonAnnee_user_adj = gtk_adjustment_new (2000, 1910, 2020, 0.5, 10, 10);
  spinbuttonAnnee_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnee_user_adj), 0, 0);
  gtk_widget_show (spinbuttonAnnee_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonAnnee_user, 480, 160);
  gtk_widget_set_size_request (spinbuttonAnnee_user, 60, 27);

  entryCin_user = gtk_entry_new ();
  gtk_widget_show (entryCin_user);
  gtk_fixed_put (GTK_FIXED (fixed1), entryCin_user, 208, 216);
  gtk_widget_set_size_request (entryCin_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCin_user), 8226);

  spinbuttonNumBV_user_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonNumBV_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonNumBV_user_adj), 0, 0);
  gtk_widget_show (spinbuttonNumBV_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonNumBV_user, 200, 400);
  gtk_widget_set_size_request (spinbuttonNumBV_user, 60, 27);

  spinbuttonVote_user_adj = gtk_adjustment_new (-1, -1, 1, 1, 10, 10);
  spinbuttonVote_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonVote_user_adj), 0, 0);
  gtk_widget_show (spinbuttonVote_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonVote_user, 200, 448);
  gtk_widget_set_size_request (spinbuttonVote_user, 60, 27);

  buttonValide_user = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (buttonValide_user);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonValide_user, 480, 648);
  gtk_widget_set_size_request (buttonValide_user, 100, 29);

  checkbuttonEtr_obs = gtk_check_button_new_with_mnemonic (_("Etrangere"));
  gtk_widget_show (checkbuttonEtr_obs);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonEtr_obs, 336, 600);
  gtk_widget_set_size_request (checkbuttonEtr_obs, 118, 24);

  checkbuttonTun_obs = gtk_check_button_new_with_mnemonic (_("Tunisienne"));
  gtk_widget_show (checkbuttonTun_obs);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbuttonTun_obs, 184, 600);
  gtk_widget_set_size_request (checkbuttonTun_obs, 118, 24);

  radiobuttonFemme_user = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonFemme_user);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonFemme_user, 344, 368);
  gtk_widget_set_size_request (radiobuttonFemme_user, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonFemme_user), radiobuttonFemme_user_group);
  radiobuttonFemme_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonFemme_user));

  radiobuttonHomme_user = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonHomme_user);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonHomme_user, 200, 368);
  gtk_widget_set_size_request (radiobuttonHomme_user, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonHomme_user), radiobuttonFemme_user_group);
  radiobuttonFemme_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonHomme_user));

  comboboxprof_user = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxprof_user);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxprof_user, 200, 536);
  gtk_widget_set_size_request (comboboxprof_user, 177, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("professeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("etudiant/e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("journaliste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("ingenieur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("directeur/ice"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("medecin "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("technicien/ne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("business man/woman"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("avocat/e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("politicien/ne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxprof_user), _("autre"));

  comboboxApp_obs = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxApp_obs);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxApp_obs, 200, 488);
  gtk_widget_set_size_request (comboboxApp_obs, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxApp_obs), _("gauche "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxApp_obs), _("droit "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxApp_obs), _("autres"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxApp_obs), TRUE);

  comboboxRole_user = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxRole_user);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxRole_user, 208, 280);
  gtk_widget_set_size_request (comboboxRole_user, 180, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("observateur "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("electeur "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxRole_user), _("agentBV"));

  buttonAfficher_user = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (buttonAfficher_user);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAfficher_user, 616, 648);
  gtk_widget_set_size_request (buttonAfficher_user, 100, 29);

  g_signal_connect ((gpointer) buttonValide_user, "clicked",
                    G_CALLBACK (on_buttonValide_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonEtr_obs, "toggled",
                    G_CALLBACK (on_checkbuttonEtr_obs_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonTun_obs, "toggled",
                    G_CALLBACK (on_checkbuttonTun_obs_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonFemme_user, "toggled",
                    G_CALLBACK (on_radiobuttonFemme_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonHomme_user, "toggled",
                    G_CALLBACK (on_radiobuttonHomme_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) comboboxprof_user, "move_active",
                    G_CALLBACK (on_comboboxprof_user_move_active),
                    NULL);
  g_signal_connect ((gpointer) comboboxApp_obs, "move_active",
                    G_CALLBACK (on_comboboxApp_obs_move_active),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficher_user, "clicked",
                    G_CALLBACK (on_buttonAfficher_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_user, ajout_user, "ajout_user");
  GLADE_HOOKUP_OBJECT (ajout_user, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_user, entryNom_user, "entryNom_user");
  GLADE_HOOKUP_OBJECT (ajout_user, entryPrenom_user, "entryPrenom_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonJour_user, "spinbuttonJour_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonMois_user, "spinbuttonMois_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonAnnee_user, "spinbuttonAnnee_user");
  GLADE_HOOKUP_OBJECT (ajout_user, entryCin_user, "entryCin_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonNumBV_user, "spinbuttonNumBV_user");
  GLADE_HOOKUP_OBJECT (ajout_user, spinbuttonVote_user, "spinbuttonVote_user");
  GLADE_HOOKUP_OBJECT (ajout_user, buttonValide_user, "buttonValide_user");
  GLADE_HOOKUP_OBJECT (ajout_user, checkbuttonEtr_obs, "checkbuttonEtr_obs");
  GLADE_HOOKUP_OBJECT (ajout_user, checkbuttonTun_obs, "checkbuttonTun_obs");
  GLADE_HOOKUP_OBJECT (ajout_user, radiobuttonFemme_user, "radiobuttonFemme_user");
  GLADE_HOOKUP_OBJECT (ajout_user, radiobuttonHomme_user, "radiobuttonHomme_user");
  GLADE_HOOKUP_OBJECT (ajout_user, comboboxprof_user, "comboboxprof_user");
  GLADE_HOOKUP_OBJECT (ajout_user, comboboxApp_obs, "comboboxApp_obs");
  GLADE_HOOKUP_OBJECT (ajout_user, comboboxRole_user, "comboboxRole_user");
  GLADE_HOOKUP_OBJECT (ajout_user, buttonAfficher_user, "buttonAfficher_user");

  return ajout_user;
}

GtkWidget*
create_afficher_user (void)
{
  GtkWidget *afficher_user;
  GtkWidget *fixed2;
  GtkWidget *treeview_user;
  GtkWidget *entryRech_user;
  GtkWidget *button_Rech_user;
  GtkWidget *buttonAjout_user;
  GtkWidget *buttonModifier_user;
  GtkWidget *buttonSupp_user;
  GtkWidget *buttonPrec_user;

  afficher_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher_user), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (afficher_user), fixed2);

  treeview_user = gtk_tree_view_new ();
  gtk_widget_show (treeview_user);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_user, 0, 48);
  gtk_widget_set_size_request (treeview_user, 1280, 472);

  entryRech_user = gtk_entry_new ();
  gtk_widget_show (entryRech_user);
  gtk_fixed_put (GTK_FIXED (fixed2), entryRech_user, 80, 8);
  gtk_widget_set_size_request (entryRech_user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRech_user), 8226);

  button_Rech_user = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button_Rech_user);
  gtk_fixed_put (GTK_FIXED (fixed2), button_Rech_user, 280, 8);
  gtk_widget_set_size_request (button_Rech_user, 100, 29);

  buttonAjout_user = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAjout_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjout_user, 1304, 96);
  gtk_widget_set_size_request (buttonAjout_user, 90, 29);

  buttonModifier_user = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonModifier_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonModifier_user, 1304, 160);
  gtk_widget_set_size_request (buttonModifier_user, 90, 29);

  buttonSupp_user = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonSupp_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSupp_user, 1304, 224);
  gtk_widget_set_size_request (buttonSupp_user, 90, 29);

  buttonPrec_user = gtk_button_new_with_mnemonic (_("Prec\303\251dent"));
  gtk_widget_show (buttonPrec_user);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonPrec_user, 48, 552);
  gtk_widget_set_size_request (buttonPrec_user, 90, 29);

  g_signal_connect ((gpointer) treeview_user, "row_activated",
                    G_CALLBACK (on_treeview_user_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_Rech_user, "clicked",
                    G_CALLBACK (on_button_Rech_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjout_user, "clicked",
                    G_CALLBACK (on_buttonAjout_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier_user, "clicked",
                    G_CALLBACK (on_buttonModifier_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupp_user, "clicked",
                    G_CALLBACK (on_buttonSupp_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonPrec_user, "clicked",
                    G_CALLBACK (on_buttonPrec_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_user, afficher_user, "afficher_user");
  GLADE_HOOKUP_OBJECT (afficher_user, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (afficher_user, treeview_user, "treeview_user");
  GLADE_HOOKUP_OBJECT (afficher_user, entryRech_user, "entryRech_user");
  GLADE_HOOKUP_OBJECT (afficher_user, button_Rech_user, "button_Rech_user");
  GLADE_HOOKUP_OBJECT (afficher_user, buttonAjout_user, "buttonAjout_user");
  GLADE_HOOKUP_OBJECT (afficher_user, buttonModifier_user, "buttonModifier_user");
  GLADE_HOOKUP_OBJECT (afficher_user, buttonSupp_user, "buttonSupp_user");
  GLADE_HOOKUP_OBJECT (afficher_user, buttonPrec_user, "buttonPrec_user");

  return afficher_user;
}

